services:
  frontend:
    image: wayshub-frontend:production
    container_name: wayshub-frontend
    ports:
      - '3000:80'
    restart: always
    stdin_open: true
    networks:
      - team2

  webserver:
    image: nginx:latest
    container_name: webserver
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./nginx/certs:/etc/nginx/certs"
    networks:
      - team2
networks:
  team2:
